const mongoose = require('mongoose');
// I don't think _id is necessary since we can let that be autogenerated
const schema = mongoose.Schema({
                                   reviewerID: String,
                                   revieweeType: {type: String, enum: ['SELLER', 'VENUE']},
                                   revieweeID: String,
                                   text: String,
                                   score: Number,
                                   date: Date,
                               }, {collection: "reviews"});
module.exports = schema;
