const mongoose = require('mongoose');
// I don't think _id is necessary since we can let that be autogenerated
const schema = mongoose.Schema({
                                   buyerID: String,
                                   sellerID: String,
                                   eventID: String,
                                   price: Number,
                                   qty: Number,
                               }, {collection: "transactions"});
module.exports = schema;
